global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'student-service'
    static_configs:
      - targets: ['student-service:8081']
    metrics_path: '/actuator/prometheus'

  - job_name: 'faculty-service'
    static_configs:
      - targets: ['faculty-service:8082']
    metrics_path: '/actuator/prometheus'

  - job_name: 'search-service'
    static_configs:
      - targets: ['search-service:8083']
    metrics_path: '/actuator/prometheus'
